### ISSUE TITLE
Add Gradle Kotlin DSL setup snippet on the website

### ISSUE THREAD

**Issue by LouisCAD** [runningcode/gradle-doctor#111]
Currently, there's a Groovy only snippet, would be great to have the setup be straightforward to Kotlin DSL users.

Also, can't the plugins DSL be used? If it can, I can submit a PR for the doc edit.

**Comment by runningcode** [comment]
Hey, good point. Yes we should include the Kotlin DSL and yes the Plugins DSL can be used. Here's how I do this on other pages: https://github.com/runningcode/gradle-doctor/blame/master/docs/configuration.md#L60

**Comment by runningcode** [comment]
Fixed via https://github.com/runningcode/gradle-doctor/pull/118

**Comment by LouisCAD** [comment]
Thanks for the improvement!
