### ISSUE TITLE
Help to update Gradle

### ISSUE THREAD

**Issue by jmfayard** [runningcode/gradle-doctor#114]
Hello Nelson, 
I have seen you talked about your project at an Android meetup in Berlin but it's the first time I take a deeper look.

There is a feature I could contribute to gradle-doctor (because I already did it here https://github.com/jmfayard/refreshVersions/issues/234 ) is to warn that a newer version of Gradle is available and remind people how to upgrade

```
You are currently running Gradle 6.1.0. 
To update to the current stable versions, run
    $ ./gradlew wrapper --gradle-version 6.6.1
```

Of course we could disable the warning as here
https://runningcode.github.io/gradle-doctor/configuration/

Is that something you are interested in?

**Comment by runningcode** [comment]
Hey, that's a great idea! If we can integrate this in to the build without affecting build performance, that would be ideal?
Or do you imagine a separate task just to check if we are up to date?

**Comment by jmfayard** [comment]
I don't know your project but I'm not sure if it makes sense to run it every time. 
Wouldn't that be just more verbose warnings that people will ignore?

**Comment by runningcode** [comment]
The Gradle Doctor works by simply applying it to your project. There are no tasks to run. It prints out suggestions at the end of the build.
I think this would make sense as a good suggestion as long as it doesn't slow down the build and there is a configuration option to disable this warning.

**Comment by jmfayard** [comment]
> if it doesn't slow down the build

It slows the build by making one HTTP call to https://services.gradle.org/versions/current
But we can cache the result and only do the call if it's not present since one week for example

**Comment by runningcode** [comment]
I'm going to close this as I think there are other plugins and tools which can help maintain your Gradle version up-to-date. Contributions are welcome though, I just don't like the idea of a solution that would add time to the build making a network call.
