### ISSUE TITLE
Ability to disable "Did you really mean to run all these?" warning

### ISSUE THREAD

**Issue by runningcode** [runningcode/gradle-doctor#124]
There are use cases where building all projects might make sense for example on CI or multiplatform projects.
We should add the ability to whitelist tasks or disable the warning.

**Comment by vanniktech** [comment]
Ideally, running the same command again would whitelist it automatically

**Comment by runningcode** [comment]
This was built for two use cases.
* Developers hitting the buidl button in Android Studio and building all modules wasting a lot of time.
* Accidentally running `assembleDebug` instead of `assembleFlavorDebug` in a large monorepo with many sample apps. This causes multiple sample apps to be assembled instead of the app you actually intended to build wasting a lot of time.

For both of the above cases, developers will tend to retry the commend 1-3 times before realizing it will always fail and then they will read the error message and try somethign else. Whitelisting the command wouldn't help in these situations.
What is the situation in which it would be helpful to show the warning and then allow the command to happen anyways? I see this warning as an "all or nothing" type of deal, either blocked or allowed.

The other issue would be where to save the "whitelist". Putting it in the build cache would only mean that it were whitelisted until the cache entry disappears, the real thing we want here is to add somehting to the configuration that would permanently allow or disallow this for all machines.

After all that discussion, I also realized this is a feature we already have.
https://github.com/runningcode/gradle-doctor/blob/master/doctor-plugin/src/main/java/com/osacky/doctor/DoctorExtension.kt#L42

just set `allowBuildingAllAndroidAppsSimultaneously = false` in the extension.

**Comment by vanniktech** [comment]
Works for me. Might be worth pointing out in the error message.
