### ISSUE TITLE
Java home not matching warning not displayed properly in Android Studio

### ISSUE THREAD

**Issue by athkalia** [runningcode/gradle-doctor#127]
Hello,

Trying out your tool (v0.6.2) in Android Studio 4.0, on Windows with the following `javaHome` config block:

```
 javaHome {
        ensureJavaHomeMatches = true
        ensureJavaHomeIsSet = true
        failOnError.set(false)
     }
```

And with JAVA_HOME not matching the build JDK on purpose, I get the following message:

![image](https://user-images.githubusercontent.com/6057808/95547680-658b4780-09fb-11eb-882e-38b1b87d229d.png)

If I set the `failOnError` flag to `true`, I then get a proper message that looks like this:

![image](https://user-images.githubusercontent.com/6057808/95547766-953a4f80-09fb-11eb-9990-942d7852db1f.png)

**Comment by runningcode** [comment]
Thanks for filing this! What version of the android gradle plugin and what version of Android Studio are you using?

**Comment by anjalsaneen** [comment]
it's happening for me as well.

AGP: gradle-6.5
Gradle Doctor: 0.6.2
Build Scan: https://scans.gradle.com/s/5qzbouyldvpey

**Comment by runningcode** [comment]
What version of the Android Gradle Plugin and what version of Android Studio are you using when this happens?
I do not see any Gradle Doctor warning in the console logs for the build scan you sent me.
https://scans.gradle.com/s/5qzbouyldvpey/console-log#L6405

**Comment by runningcode** [comment]
Closing for lack of feedback. Please re-open if this is happening.
