### ISSUE TITLE
Logic error in RemoteCacheEstimation

### ISSUE THREAD

**Issue by mr3y-the-programmer** [runningcode/gradle-doctor#131]
I think your formula to calculate `*MBSavings` is incorrect, here in this code snippet:
```
val oneMBTime = cacheSizeMB
val twoMBTime = cacheSizeMB / 2f
val tenMBTime = cacheSizeMB / 10f

val oneMBSavings = executionTimeSec - oneMBTime
val twoMBSavings = executionTimeSec - twoMBTime
val tenMBSavings = executionTimeSec - tenMBTime
```
You had subtracted `oneMBTime`(*in MB*) from `executionTime`(*in sec*), which isn't mathematically valid because you had subtracted different *quantities*, Hence we get incorrect results

**Comment by runningcode** [comment]
Hey, thanks for filing this. I'm not sure I fully understand. What would be the correct solution or alternative?

The unit for the `oneMBTime` should be seconds as it is the amount of time needed to download the cacheSizeMB from the cache at 1 MB/s. The forumla is cacheSize (`MB`) / 1 (`MB/s`) = `s`.

**Comment by mr3y-the-programmer** [comment]
Thanks for your response, I have tested this out with My proposal and it gave the same results, So the results are correct I was mistaken. Just the way of how it is calculated made me think there is something wrong, I have calculated it as follows:
![download](https://user-images.githubusercontent.com/26522145/99272762-d6aaef80-2830-11eb-9692-ba84931717a2.png)

So as you see, Just the implementation that is different, but in the end, we get deterministic results
