### ISSUE TITLE
Wrong link on the docs icon

### ISSUE THREAD

**Issue by AlbertVilaCalvo** [runningcode/gradle-doctor#142]
Clicking on the top-left icon in https://runningcode.github.io/gradle-doctor/ brings you to https://runningcode.github.io/fladle/

Looks like a copy-paste error.

It seems that the problem is here:  https://github.com/runningcode/gradle-doctor/blob/master/mkdocs.yml#L11

**Comment by runningcode** [comment]
Thanks for reporting.
