### ISSUE TITLE
questions about negativeAvoidanceThreshold

### ISSUE THREAD

**Issue by manask88** [runningcode/gradle-doctor#159]
https://runningcode.github.io/gradle-doctor/configuration/

**Comment by manask88** [comment]
what units are used for negativeAvoidanceThreshold? is it nanoseconds? 
also, is there a way to disable Slower From Cache checks? I was considering increasing the threashold value, but it seems like it only supports ints, so might not be able to use a big enough number

**Comment by runningcode** [comment]
1. milliseconds.

2. for the slower  from cache checks, what values are you seeing in your project where using the largest or smallest `Integer` is not big enough?

**Comment by manask88** [comment]
For slower cache, i was using 99999999, but planning to switch to 2147483647 and see if it makes a difference

**Comment by runningcode** [comment]
And how much slower are the these tasks when they are being pulled from the cache? Are they 99999999ms slower to pull from the cache than they originally took to execute? You can use a build scan to tell you this information.

**Comment by runningcode** [comment]
Please share a build scan if you can and re-open the ticket.
