### ISSUE TITLE
Parallel GC option required, doesn't seem to get recognized when the used jdk isn't the bundled one/8

### ISSUE THREAD

**Issue by carstenhag** [runningcode/gradle-doctor#160]
Tried to set the parallel GC flag by

* `org.gradle.jvmargs=-XX\:MaxPermSize\=512m -XX\:+UseParallelGC` inside `gradle.properties` file.

* `via CLI (`JAVA_OPTS`:
```
JAVA_OPTS="-XX:MaxPermSize=512m -XX:+UseParallelGC" ./gradlew run assembleBrandXEnvIntegrationDebug 
OpenJDK 64-Bit Server VM warning: Ignoring option MaxPermSize; support was removed in 8.0

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'dcs-app-development-android'.
> =============================== Gradle Doctor Prescriptions ============================================
  | For faster builds, use the parallel GC.                                                              |
  | Add -XX:+UseParallelGC to the org.gradle.jvmargs                                                     |
  ========================================================================================================
```
(also tried `JAVA_OPTS="-XX\:MaxPermSize\=512m -XX\:+UseParallelGC" ./gradlew run assembleBrandXEnvIntegrationDebug`)

JDK versions tested:
* /usr/libexec/java_home -v 12: /Library/Java/JavaVirtualMachines/jdk-12.0.1.jdk/Contents/Home
* /usr/libexec/java_home -v 11: /Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home

```
Android Studio 4.1.3
Build #AI-201.8743.12.41.7199119, built on March 11, 2021
Runtime version: 1.8.0_242-release-1644-b3-6915495 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.16
GC: ParNew, ConcurrentMarkSweep
Memory: 1237M
Cores: 12
Registry: ide.new.welcome.screen.force=true, external.system.auto.import.disabled=true
Non-Bundled Plugins: org.jetbrains.kotlin, com.google.developers.certification.android
```
Gradle 6.8.3

----

It *does* work with the bundled JDK though (`/Applications/Android Studio.app/Contents/jre/jdk/Contents/Home`) which is likely a JDK 8. So maybe the flag doesn't get detected correctly for JDK 9 and higher?

**Comment by runningcode** [comment]
Thanks for reporting. What happens if you use `-XX:+UseParallelGC` instead of `-XX\:+UseParallelGC`?

**Comment by burntcookie90** [comment]
we are using `-XX:+UseParallelGC` on jdk 11 and having this same error

**Comment by runningcode** [comment]
@burntcookie90 can you paste the output of `./gradlew --version` as well as your `org.gradle.jvmargs` in your Gradle home and in your project?

**Comment by burntcookie90** [comment]
```
» ./gradlew --version

------------------------------------------------------------
Gradle 7.0.2
------------------------------------------------------------

Build time:   2021-05-14 12:02:31 UTC
Revision:     1ef1b260d39daacbf9357f9d8594a8a743e2152e

Kotlin:       1.4.31
Groovy:       3.0.7
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          11.0.11 (Red Hat, Inc. 11.0.11+9)
OS:           Linux 5.12.13-300.fc34.x86_64 amd64
```

`project/gradle.properties`:
```
org.gradle.jvmargs=-Xmx6144m -XX:MaxPermSize=512m -XX:+UseParallelGC
```

`~/.gradle/gradle.properties`:
```
org.gradle.jvmargs=-Xmx8g -XX:MaxPermSize=2048m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
```

**Comment by runningcode** [comment]
Please ensure that the highest priority `org.gradle.jvmargs` are configured to have `-XX:+UseParallelGC`. In this case your `~/.gradle/gradle.properties` is not configured to use `-XX:+UseParallelGC`.

You can read more about the order of precedence here: https://docs.gradle.org/current/userguide/build_environment.html#sec:gradle_configuration_properties
