### ISSUE TITLE
Unable to set JAVA_HOME in Android Studio Arctic Fox 

### ISSUE THREAD

**Issue by snpefk** [runningcode/gradle-doctor#174]
In arctic fox version Android Studio options for set project JDK through `JAVA_HOME` is missing. 
It seems like "Arctic Fox" version of Android Studio rework settings for "Project Structure" (moving JDK Location to Gradle Settings) and Gradle JDK combobox doesn't show `JAVA_HOME` option in "Gradle JDK" setting (although, I set env in `.zshrc` and even in `.profile`, just to be sure). 
![Screenshot from 2021-10-14 17-38-03](https://user-images.githubusercontent.com/2883201/137347474-f4922296-7104-4091-8b56-80b152138973.png)

As workaround I'm disabled `failOnError`, but recommendation specified [on this page](https://runningcode.github.io/gradle-doctor/java-home/) does not work for me.

**Comment by rciovati** [comment]
FYI you can also use the `STUDIO_GRADLE_JDK` env variable instead of setting `JAVA_HOME` manually in the ide ([source](https://developer.android.com/studio/command-line/variables#envar))

**Comment by Drjacky** [comment]
@rciovati Didn't help. I still get the error on AS 2021.1.1:
```bash
A problem occurred configuring root project 'MVVMTemplate'.
> =============================== Gradle Doctor Prescriptions ============================================
  | JAVA_HOME is not set.                                                                                |
  | Please set JAVA_HOME so that switching between Android Studio and the terminal does not trigger a fu |
  | ll rebuild.                                                                                          |
  | To set JAVA_HOME: (using bash)                                                                       |
  | echo "export JAVA_HOME=$(/usr/libexec/java_home)" >> ~/.bash_profile                                 |
  | or `~/.zshrc` if using zsh.                                                                          |
  |                                                                                                      |
  ========================================================================================================

```
While the JAVA_HOME is set

**Comment by ColtonIdle** [comment]
Looks like it's an issue because of intellij https://issuetracker.google.com/issues/216364005
https://twitter.com/softwarejameson/status/1486192383716909057

**Comment by runningcode** [comment]
Closing since this is an issue in intellij.
