### ISSUE TITLE
Add warning for enabling build cache?

### ISSUE THREAD

**Issue by ColtonIdle** [runningcode/gradle-doctor#177]
Watching this: https://youtu.be/S_zZRBJxTQ0?t=201

And I thought I had build cache enabled... but I didn't. Would've thought gradle doctor would've warned me about it? What do you think runningcode ?

**Comment by dsvoronin** [comment]
@ColtonIdle it's not clear what cache exactly do you mean.
Video starts with last seconds of lint caching section and starts about configuration cache

general `org.gradle.caching=true` is not experimental and could be a subject for a warning indeed, but `configuration cache` is experimental and it looks like your issue description confused @oheyadam

**Comment by runningcode** [comment]
I think this warning would generate too many false positives and would not be useful. I have not yet come across an Android project that did not already have this enabled since the default Android Studio template adds this.

**Comment by ColtonIdle** [comment]
Really? I created a new project about a month ago and it did not have this, hence why I created this issue. I'm using the AS canaries exclusively... I wonder if something was up with that.

It's fine to close if you think there'd be too many false positives. Thanks Nelson
