### ISSUE TITLE
False positive detection + recommendation for GC with JDK17+

### ISSUE THREAD

**Issue by ubiratansoares** [runningcode/gradle-doctor#181]
With the release of* JDK17, [ZGC is considered production-ready](https://malloc.se/blog/zgc-jdk17).

However, when applying

```
-XX:+UseZGC
```
for my JVM args Gradle Doctor complains that I'm not using the recommend [Parallel GC](https://github.com/runningcode/gradle-doctor/blob/master/doctor-plugin/src/main/java/com/osacky/doctor/JavaGCFlagChecker.kt#L15). 

I have an Android project which is fully ready for JDK17 (using Gradle 7.3 and Kotlin 1.6.0) and I wanted to benchmark some builds with ZGC since [it seems to deliver great throughput with shorter GC pauses](https://kstefanj.github.io/2021/11/24/gc-progress-8-17.html); in my case I can opt-out from the GC prescription if I want so I can proceed with the benchmarks at all. 

However I was wondering if we could improve the actual Gradle Doctor prescription by 

- supporting at least the all production-ready GC implementations for JDK9+ LTS releases
- suggesting the proper GC flags according the LTS release, following recommendations from tooling providers (eg, [Google](https://developer.android.com/studio/build/optimize-your-build?hl=nl#configure-the-jvm-garbage-collector)) and/or community consensus around GC performance (eg, with public documented benchmarks around and etc)

This feature request is not critical for the short term since JDK17 just landed. I'd be happy to raise a PR around it. 🙂

**Comment by runningcode** [comment]
Thanks @ubiratansoares . Are there any benchmarks that show that ZGC is faster than the parallel GC for Gradle builds? If so I'm happy to accept this change.

**Comment by ubiratansoares** [comment]
The article I've linked shows some GC benchmarks using [SPECjbb® 2015](https://www.spec.org/jbb2015/), but I'm not sure how realistic such results are in the specific context of Gradle builds. 

Are you aware of any existing benchmarks comparing GC impact for G1 and Parallel in Gradle builds? Asking because they could be a good starting point to evaluate ZGC as well :)

**Comment by runningcode** [comment]
Thanks @ubiratansoares . The results for SPECjbb are not relevant for Android builds. Those results also show that G1 is faster than Parallel for those applications. The opposite, however, is true for Gradle builds especially Android Gradle builds.
Google has done several internal benchmarks showing that Parallel GC is faster than G1 which is why they make that recommendation on their website. I have also done a benchmark here to show that it is faster for build performance:
https://github.com/uber-common/android-build-eval/pull/3

**Comment by runningcode** [comment]
This is the only benchmark I've found: https://twitter.com/mreichelt/status/1464010532059586562

**Comment by ubiratansoares** [comment]
Hey @runningcode, I'll close this one for now; if eventually we have some numbers / benchmarks pointing to a good fit for ZGC in Gradle projects - maybe with some other GC-tuning shenanigans! - I'd be happy to re-open this issue :) 

Thanks for the pointers you've shared!

**Comment by morj** [comment]
@ubiratansoares have you tried `-XX:+UseShenandoahGC` as well?

**Comment by ubiratansoares** [comment]
@morj Actually not, have you? 👀
