### ISSUE TITLE
UseParallelGC warning makes the build fail despite being already present inside the gradle.properties file

### ISSUE THREAD

**Issue by leinardi** [runningcode/gradle-doctor#182]
I've enabled the plugin on a new project that already has an entry for the `-XX:+UseParallelGC` inside the `org.gradle.jvmargs`, but the plugin still complains that is missing. Am I doing something wrong or is this a bug of the plugin?

The `-XX:+UseParallelGC` is [added to the `gradle.properties` file](https://github.com/leinardi/Forlago/blob/84422b50c138de576566b53397345b46d291261a/gradle.properties#L19), as suggested by the [official Android documentation](https://developer.android.com/studio/build/optimize-your-build).

A repro project can be found here: https://github.com/leinardi/Forlago/tree/gradle-doctor

**Comment by runningcode** [comment]
Can you please share with me the contents of you `gradle.properties` in your gradle home? `~/.gradle/gradle.properties`?

**Comment by leinardi** [comment]
Sure, this is the entire content of the file:
```
$ cat ~/.gradle/gradle.properties
#org.gradle.configureondemand=true
org.gradle.daemon=true
org.gradle.daemon.idletimeout=1200000
org.gradle.caching=false
org.gradle.parallel=false

org.gradle.jvmargs="-Djdk.http.auth.tunneling.disabledSchemes=''"

gradle.publish.key=<redacted>
gradle.publish.secret=<redacted>
bintrayUser=<redacted>
bintrayApiKey=<redacted>
jenkinsUser=<redacted>
jenkinsToken=<redacted>
```
And, as you can see, there is no `org.gradle.jvmargs` declared there.

**Comment by leinardi** [comment]
Oh yeah: commenting the line `org.gradle.jvmargs="-Djdk.http.auth.tunneling.disabledSchemes=''"` fixed the issue! Thanks!
