### ISSUE TITLE
" this build needs more heap space." Which heap should I increase?

### ISSUE THREAD

**Issue by ColtonIdle** [runningcode/gradle-doctor#190]
I was greeted with this warning today. I'm a noob at this whole jvmargs/vs kotlin args/vs gradle daemon args, etc.

Where would I allocate more heap space? Do I give it to the IDE?

```
=============================== Gradle Doctor Prescriptions ============================================
| This build spent 76% garbage collecting.                                                             |
| If this is the first build with this Daemon, it likely means that this build needs more heap space.  |
| Otherwise, if this is happening after several builds it could indicate a memory leak.                |
| For a quick fix, restart this Gradle daemon. ./gradlew --stop                                        |
========================================================================================================
```

**Comment by runningcode** [comment]
This specifically refers to only the heap space of the Gradle build daemon. There are a few ways to set it but most projects set it using the jvm args in the project's `gradle.properties` file.
Here is an example of where this is set for the Gradle Doctor: https://github.com/runningcode/gradle-doctor/blob/master/gradle.properties#L1

PR's welcome to make this message or relevant documentation more clear.

**Comment by ColtonIdle** [comment]
Thanks for confirming!
