### ISSUE TITLE
JAVA_HOME bumblebee issue 

### ISSUE THREAD

**Issue by jonnycaley** [runningcode/gradle-doctor#192]
After updating to the release of Android Studio Bumblebee `System.getEnv("JAVA_HOME")` returns null, which causes the plugin to throw an exception when comparing to the JDK version.

Although it's not an issue with your plugin I thought it would still be worth letting you know 😄

There's an issue open here with some workarounds - https://issuetracker.google.com/issues/216364005

**Comment by runningcode** [comment]
Thanks for the info. See also: https://github.com/runningcode/gradle-doctor/issues/174#issuecomment-1022302834
