### ISSUE TITLE
On which repository is this plugin stored?

### ISSUE THREAD

**Issue by VladSVAssets** [runningcode/gradle-doctor#193]
I receive the following error after adding the plugin on the build.gradle ( plugins { id 'com.osacky.doctor' version "0.7.3" } ):

* Exception is:
org.gradle.api.plugins.UnknownPluginException: Plugin [id: 'com.osacky.doctor', version: '0.7.3'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (could not resolve plugin artifact 'com.osacky.doctor:com.osacky.doctor.gradle.plugin:0.7.3')

Is this plugin compatible with Java 11?

The readme did not help very much, nor the https://runningcode.github.io/gradle-doctor/.

**Comment by runningcode** [comment]
The plugin is available in the [Gradle Plugin Portal](https://plugins.gradle.org/plugin/com.osacky.doctor) and [Maven Central](https://mvnrepository.com/artifact/com.osacky.doctor/doctor-plugin/0.7.3).

It is fully compatible with Java 11

**Comment by VladSVAssets** [comment]
This works, thank your for the help.
