### ISSUE TITLE
Detect Kotlin daemon fallback strategy

### ISSUE THREAD

**Issue by eugene-krivobokov** [runningcode/gradle-doctor#194]
### The problem

There is a problem with the Kotlin daemon. In case of failure, it silently falls into fallback mode. This could slow down the build by several times.
```
Could not perform incremental compilation: Could not connect to Kotlin compile daemon
Could not connect to kotlin daemon. Using fallback strategy.
```
Here is more details: https://youtrack.jetbrains.com/issue/KT-48843

### Proposal

Detekt and fail the build. A warning in many cases is not enough because there are already warnings in logs from the compiler.

Feel free to reuse sample implementation from https://github.com/avito-tech/avito-android/pull/1326

**Comment by runningcode** [comment]
Thanks for filing this. This is a good idea to implement!
