### ISSUE TITLE
Add project name information when printing prescriptions

### ISSUE THREAD

**Issue by mformetal** [runningcode/gradle-doctor#199]
A project I work in has multiple included but independent builds that all apply the Gradle Doctor plugin. When run in aggregate, there are multiple pill boxes of prescriptions but the project it's printed for isn't in the logs. It would be useful if the title in these pill boxes read something like:

```
"=========================== Gradle Doctor Prescriptions for project NAME ===============================")
```

So I could clearly see that this message is for project X, that message is for project Y, etc. 

I've already done so by making a branch and testing it, but it seems like this repository doesn't allow public contributors.

**Comment by runningcode** [comment]
That sounds like a good idea. I'm not sure if the best place would be in the title or in the message itself. We can consider both possibilities.

Out of curiousity: what makes you think that this repository doesn't allow public contributors? A few features and bug fixes have been contributed to by the community in the past.

**Comment by mformetal** [comment]
Odd, I tried pushing a branch and got a bunch of auth errors, guess I just haven't configured git correctly. 

The title seemed to make the most sense to me, as it allows you to quickly scan a bunch of logs and easily filter out stuff you don't want to see/don't care about. Would you prefer otherwise?

**Comment by runningcode** [comment]
Can you give an example of a prescription which is project specific and the prescription itself doesn't include the project name?

Please fork the repository and submit a pull request from your fork.

**Comment by mformetal** [comment]
I should also mention that I will try to get my team not to run the aggregate project, but the independent projects themselves, so this should be a non-issue in the long-term future, but I think the extra information doesn't hurt for now.

**Comment by runningcode** [comment]
Can you please share a sample of your project structure for me to better understand this?
Do you have the doctor plugin applied multiple times?

**Comment by mformetal** [comment]
> Can you please share a sample of your project structure for me to better understand this? Do you have the doctor plugin applied multiple times?

I can't share the internals of this project as it's private, but essentially we have this structure:

```
app1
    build.gradle.kts
        apply plugin: gradle-doctor
    settings.gradle.kts
app2
    build.gradle.kts
        apply plugin: gradle-doctor
    settings.gradle.kts
settings.gradle.kts
   // In reality these builds are conditionally included, but for simplicity's sake just hardcoding the example
   includeBuild "app1" 
   includeBuild "app2" 
```

Yes, we have the doctor plugin applied multiple times because each build is technically independent, but we still have a root aggregate project that devs on my team can run. When a dev runs the root gradlew-wrapper, each independent build is configured, so each doctor-plugin does its thing. 

I'm trying to move us away from any root configuration, so eventually this whole github issue will become defunct since there will only be one project with the doctor-plugin applied.

**Comment by runningcode** [comment]
Thanks for sharing. This is an extremely rare setup. I don't recommend applying the Gradle Doctor plugin so many times.
I do not wish to complicated the codebase for such a case. If it comes up again I may reconsider.

**Comment by mformetal** [comment]
Word, thanks for engaging with me!
