### ISSUE TITLE
[Question] Get disabling caching warning even by setting the negativeAvoidanceThreshold

### ISSUE THREAD

**Issue by Drjacky** [runningcode/gradle-doctor#207]
When I run `./gradlew buildHealth` from `com.autonomousapps.dependency-analysis` plugin, I still get this warning:
```groovy
=============================== Gradle Doctor Prescriptions ============================================
| The following operations were slower to pull from the cache than to rerun:                           |
| :presentation:graphViewReleaseTest                                                                   |
| Consider disabling caching them.                                                                     |
| For more information see: https://runningcode.github.io/gradle-doctor/slower-from-cache/             |
========================================================================================================

```
even when I set either of
```kotlin
doctor {
    disallowMultipleDaemons = true
    negativeAvoidanceThreshold = 500
    warnWhenJetifierEnabled = true

    javaHome {
        ensureJavaHomeIsSet = true
        ensureJavaHomeMatches = true
        failOnError.set(true)
    }
}

```
or
```kotlin
configure<com.osacky.doctor.DoctorExtension> {
    disallowMultipleDaemons.set(false)
    negativeAvoidanceThreshold.set(500)
    warnWhenJetifierEnabled.set(true)

    javaHome {
        ensureJavaHomeIsSet.set(true)
        ensureJavaHomeMatches.set(true)
        failOnError.set(true)
    }
}
```

**Comment by runningcode** [comment]
Did the task take longer to pull from the cache than it took to rerun?
What was the original execution time? What was the cached execution time?

**Comment by Drjacky** [comment]
With `negativeAvoidanceThreshold`:
BUILD SUCCESSFUL in 19s

Without `negativeAvoidanceThreshold`:
BUILD SUCCESSFUL in 5s

**Comment by Drjacky** [comment]
If I understood you correctly,

`org.gradle.caching=false`
&
`org.gradle.caching.debug=false`:

`./gradlew graphViewReleaseTest` ->
> BUILD SUCCESSFUL in 5s
_______
`org.gradle.caching=false`
&
`org.gradle.caching.debug=false`
&
`configurations.all { resolutionStrategy.cacheChangingModulesFor(0, "seconds") }`:

`./gradlew graphViewReleaseTest` -> 
> BUILD SUCCESSFUL in 4s
_______
`org.gradle.caching=true`
&
`org.gradle.caching.debug=true`
&
`negativeAvoidanceThreshold.set(500)`:

`./gradlew graphViewReleaseTest` ->
> BUILD SUCCESSFUL in 6s


Note: in all of them it did not print the caching warning.

**Comment by runningcode** [comment]
Hi, the warning works on an individual task basis and reports whether each individual task was worth pulilng from the build cache.
You have reported to me the durations for your entire build.
A build scan can tell you the invidividual durations of each task. Otherwise there does not appear to be a bug here.
