### ISSUE TITLE
Incompatible with Kotlin 1.7.0-Beta

### ISSUE THREAD

**Issue by ZacSweers** [runningcode/gradle-doctor#208]
Kotlin 1.7.0-Beta appears to have changed/removed a kapt API gradle-doctor uses

<img width="1136" alt="image" src="https://user-images.githubusercontent.com/1361086/167034491-5679f1f2-496e-4f13-834b-572c059ed221.png">

**Comment by runningcode** [comment]
Thanks for filing. Will look in to this.
