### ISSUE TITLE
Phone/Wear Modules: Did you really mean to run all these? 

### ISSUE THREAD

**Issue by zoltish** [runningcode/gradle-doctor#216]
**Since including a wear module in my project, Ill run into this message every once in a while. The message is clear and I can understand _why_ it comes up; but Id love for a way to suppress/disable it!** 

My wear module adds <1 second to the overall build time, and whenever I intentionally want to "build the entire project"; its usually coupled with some refactoring work where both my phone & wear modules will require some tweaks. The build project tool just makes it a lot easier as it mentions all the spots where I need to make tweaks in one place.

Assembling phone & wear separately works, but then its just way faster to temporarily disable the plugin, build the entire project, and re-enable it.

```
=============================== Gradle Doctor Prescriptions ============================================
| Did you really mean to run all these? [task ':app:phone:assembleDebug', task ':app:wear:assembleDebu |
| g']                                                                                                  |
| Maybe you just meant to assemble/install one of them? In that case, you can try                      |
|   ./gradlew phone:assembleDebug                                                                      |
| Or did you hit "build" in the IDE (Green Hammer)? Did you know that assembles all the code in the en |
| tire project?                                                                                        |
| Next time try "Sync Project with Gradle Files" (Gradle Elephant with Arrow).                         |
========================================================================================================
```

**Comment by runningcode** [comment]
You can set `allowBuildingAllAndroidAppsSimultaneously = true` in the configuration options to disable this warning.

**Comment by zoltish** [comment]
I dont know how I missed that, but Im grateful that you pointed me in its direction. Thank you!
