### ISSUE TITLE
Potential memory leak

### ISSUE THREAD

**Issue by lwasyl** [runningcode/gradle-doctor#247]
I'm not sure if it's actually a leak, just when investigating unrelated issue I noticed that the plugin keeps a lot of stuff on the heap:

<img width="1579" alt="image" src="https://user-images.githubusercontent.com/3951580/213530067-c8fc5088-99b0-41f1-b033-11a63a159c2f.png">

That's heapdump after Gradle crashed with OOM, I'm pretty confident gradle-doctor is _not_ the culprit but the amount of memory retained seems a bit suspicious regardless I think

**Comment by runningcode** [comment]
It retains the build operations over the course of a build in order to do the tallying and math. These should be dropped after a build completes. Are you seeing that these are retained over the course of several builds?

**Comment by lwasyl** [comment]
Yep, I filed it just in case because I saw something out of the ordinary, but that was heap dumped on OOM, so there wasn't an opportunity to clean up stuff I guess. 

I checked now and after a build and GC I don't see many references in plugin's classes 👍 So seems all is good
