### ISSUE TITLE
Java home symlink

### ISSUE THREAD

**Issue by emartynov** [runningcode/gradle-doctor#40]
So I use sdkman to manage my sdk versions.

When I try to use this plugin I get:
 | JAVA_HOME is /Users/e/.sdkman/candidates/java/current
 | Gradle is using /Users/e/.sdkman/candidates/java/8.0.242.hs-adpt     

JAVA_HOME is actually a symlink that points to the folder which is printed as used by Gradle.

**Comment by runningcode** [comment]
oh interesting! with this setup, how can we check that current points to the same version that gradle is using?

**Comment by emartynov** [comment]
Maybe operate not with the strings but with the files https://stackoverflow.com/questions/28371993/resolving-directory-symlink-in-java

**Comment by emartynov** [comment]
Just quickly tested it:

`import java.io.File

val file1 = File("/Users/e/.sdkman/candidates/java/8.0.242.hs-adpt")
val file2 = File("/Users/e/.sdkman/candidates/java/current")

file1 == file2 //false

file1.absoluteFile == file2.absoluteFile //false

file1.absolutePath == file2.absolutePath //false

val path1 = file1.toPath().toRealPath()
val path2 = file2.toPath().toRealPath()

path1 == path2 //true
`

**Comment by runningcode** [comment]
You rock! i'll test this out
