### ISSUE TITLE
Cannot apply gradle doctor from external script?

### ISSUE THREAD

**Issue by louistsaitszho** [runningcode/gradle-doctor#51]
Example: [click here](https://github.com/louistsaitszho/gradle-doctor-test/commit/90816f147b4f15de33c954b50edf108bffabd488#diff-39e7d8c00954e920b98e7636f0ac30b2R4)

We'd like to add gradle-doctor to our repo, but developers can opt-in. And when I try to move the configuration to an external script, it breaks gradle-doctor, due to [this line](https://github.com/runningcode/gradle-doctor/blob/master/doctor-plugin/src/main/java/com/osacky/doctor/DoctorPlugin.kt#L82) not able to find `KotlinPluginWrapper`.

Is there another way to show processing time of kapt, or is there another way to apply plugin from external script?

**Comment by runningcode** [comment]
Hey, thanks for the example. This is a good point, the Gradle Doctor assumes that Kotlin and Android are on the classpath and it shouldn't.

That being said, if it were to silently ignore the fact that they aren't on the classpath then the plugin itself wouldn't work.

I'm curious why you want developers to opt in to the plugin?

Anyways, the easiest way to create the opt-in logic is like so:
```
if (project.getProperty("DOCTOR").toBoolean()) {
  apply plugin: 'com.osacky.doctor'
}
```
Keep the plugin on the buildscript classpath. There is no need to move the plugin to an external buildscript.
It's best not to dynamically change the buildscript classpath as it will cause the entire project to be rebuilt.

**Comment by louistsaitszho** [comment]
> I'm curious why you want developers to opt in to the plugin?

Technically gradle doctor not a "must have" or anything, and if someone does not like to see those warnings, it would be nice to be able to disable them completely.

There is also a bit of "if something went wrong with Gradle Doctor, there should be a easy way to turn it off completely", and being able to make sure absolutely 0 extra dependencies are being pull would be nice.

> it will cause the entire project to be rebuilt.

In this configuration, we expect people to just turn it on in their machine and mostly forget about it, so the occasional rebuilding shgould not be a big issue

**Comment by runningcode** [comment]
If you want to guarantee that 0 extra dependencies are being pulled it, you'll need to wrap the the dependencies block behind that flag as well. I wouldn't recommend putting the application of this plugin in a separate buildscript because it will isolate it from the rest of your project and likely won't work.

**Comment by runningcode** [comment]
Feel free to re-open if you still have issues.
