### ISSUE TITLE
JAVA_HOME issue with Android Studio

### ISSUE THREAD

**Issue by sonicdebris** [runningcode/gradle-doctor#91]
I am experiencing this issue with AS with Gradle Doctor enabled, where I get the `JAVA_HOME is not set.` error when running gradle-doctor during project configuration. 

The root cause seems to be Android Studio keeping a wrong value for `JAVA_HOME`, and I reported that here:
https://issuetracker.google.com/issues/162313337

Since Gradle Doctor's error persists after manually selecting the same path as `JAVA_HOME` from `File -> Project Structure -> SDK Location -> JDK location` in Android Studio, which should ensure that the same JDK is used for AS and terminal, I thought there might be some issue with Gradle Doctor as well, or that at least you might have some additional insight on this.

**Comment by runningcode** [comment]
Have you set the `JAVA_HOME` environment variable?
The error message should have the instructions on how to do this.
I believe the following works on unix systems.
`echo "export JAVA_HOME=${'$'}(/usr/libexec/java_home)" >> ~/.bash_profile`.

Are you on windows?

**Comment by sonicdebris** [comment]
I am on Ubuntu 20.04 (it happens on Arch as well), and yes, I've set `JAVA_HOME` (`echo $JAVA_HOME` in terminal will show the expected result).

**Comment by runningcode** [comment]
Have you restarted both Android Studio and your console after setting `JAVA_HOME`? Can you print here the exact error message you are seeing?

**Comment by sonicdebris** [comment]
Exact error:
```
> =============================== Gradle Doctor Prescriptions ============================================
  | JAVA_HOME is not set.                                                                                |
  | Please set JAVA_HOME so that switching between Android Studio and the terminal does not trigger a fu |
  | ll rebuild.                                                                                          |
  | To set JAVA_HOME: (using bash)                                                                       |
  | echo "export JAVA_HOME=$(/usr/libexec/java_home)" >> ~/.bash_profile                                 |
  | or `~/.zshrc` if using zsh.                                                                          |
  ========================================================================================================
```
And yes, tried restarting AS, restarting my machine, and this actually happens on a fresh install of AS and both in stable, beta and canary. I've experienced it on Ubuntu when we enabled gradle-doctor and I am working around it by exporting `JAVA_HOME` at the top of the AS `studio.sh` launch script. Then today a colleague installed AS stable on ARCH (with `JAVA_HOME` already defined correctly), and experienced the same.

From what I can tell, it looks like AS has a wrong or no value for `JAVA_HOME` (it cannot "retrieve" it from the system on start for some reason). Then gradle-doctor will be run during project sync in AS and it likely relies on JAVA_HOME as "known" by the IDE.

**Comment by sonicdebris** [comment]
Running `studio.sh` from terminal works so at this point I think it's some issue with Gnome...

**Comment by sonicdebris** [comment]
Ok, apparently I was exporting `JAVA_HOME in `.bash_rc`, but Gnome needs it to be exported in `.profile` for it to work with GUI applications launched from the menu.

I wouldn't see that because `echo $JAVA_HOME` would of course work, and even running `export JAVA_HOME=...` in terminal would have no effect in launching AS from gnome's menu.

Adding the `export JAVA_HOME=...` line in `$HOME/.profile` solves all problems. Sorry for the confusion, I'll close this and hope the info is useful to some other poor soul with the same issue!

**Comment by burntcookie90** [comment]
Just a heads up: I ran into this just now on Fedora 32 with Cinnamon. I'm guessing this will be an issue with anyone using gnome based DEs. It might be useful to detect the OS and append this issue or message to the "Prescription"

**Comment by shredderskelton** [comment]
I also was unable to solve this problem on Ubuntu 20.04.3 and Gnome 3.36.8. I ended up editting the studio.sh file, adjusting the logic in the script to favour JAVA_HOME over all other when determining which JDK to use:

```
# START EDIT
JAVA_HOME=/home/freddy/Applications/android-studio/jre
# Favour JAVA_HOME for gradle doctor
if [ -z "$JDK" -a  -n "$JAVA_HOME" -a -x "$JAVA_HOME/bin/java" ]; then
  JDK="$JAVA_HOME"
fi
# END EDIT

# ---------------------------------------------------------------------
# Locate a JDK installation directory which will be used to run the IDE.
# Try (in order): STUDIO_JDK, studio.jdk, ./jre64, JDK_HOME, JAVA_HOME, "java" in PATH.
# ---------------------------------------------------------------------
```

I assume this will be overwritten with each Android Studio update... so not a great solution

**Comment by Drjacky** [comment]
The issue still exists on macOS; I have these lines
```
export JAVA_HOME=$(/usr/libexec/java_home)
echo "export JAVA_HOME=${'$'}(/usr/libexec/java_home)" >> ~/.bash_profile
```
in both zchrc and bash_profile.

**Comment by thuytrinh** [comment]
I believe this is related to https://github.com/runningcode/gradle-doctor/issues/188.

Somehow while Android Studio was still open, my MacBook crashed. And after restarting it, I ran into this issue and the issue https://github.com/runningcode/gradle-doctor/issues/188.

My Android Studio was installed manually before. I didn't use the IntelliJ Toolbox app. The `JAVA_HOME` was already exported in the `.zshrc` file. My iTerm2 can still recognize this and can echo `JAVA_HOME` correctly.

I have another IntelliJ version installed too but it doesn't have this issue. I could check this by comparing the Environment variables sheet in Preferences between IntelliJ and Android Studio.

I tried clearing caches in the `~/Library/{Preferences, Caches, Logs, Application Support}` directories. None worked. Also tried the Invalidate Caches & Restart option. Didn't work. Re-installing manually and via the Toolbox app. Still didn't work.

The only trick that worked for me so far is to *launch the Android Studio app via terminal*. For example, assume Android Studio is installed at: `/Users/MY_USER_NAME/Library/Application\ Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/211.7628.21.2111.8092744/Android\ Studio.app`. Then I can launch via Terminal by running:

```
open /Users/MY_USER_NAME/Library/Application\ Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/211.7628.21.2111.8092744/Android\ Studio.app
```

After doing this, I could see the Environment variables loaded correctly in Android Studio.

**Comment by Drjacky** [comment]
@thuytrinh No need for that long path. Just: `open /Applications/Android\ Studio.app`

**Comment by thuytrinh** [comment]
> @thuytrinh No need for that long path. Just: `open /Applications/Android\ Studio.app`

Thanks. That also works if you install manually. In my case, after all I installed via the Toolbox app.

**Comment by cbalea** [comment]
Had the same issue when upgrading to Bumblebee. Downgrading to Arctic Fox fixed the issue.

**Comment by marcioarantes-ww** [comment]
OS X Monterey running Bumblebee with Toolbox here. Android Studio is missing from Applications folder and unless you manually launch it from terminal it fails to see JAVA_HOME as mentioned above. Don't you love when people break your dev environment?

**Comment by runningcode** [comment]
Hi everyone. This is a Github issue about the Gradle Doctor Gradle Plugin. This issue has been closed since there is no problem with the Gradle Doctor plugin.
For issues with Android Studio and the Android Gradle Plugin, please file issues here: https://issuetracker.google.com/
For issues with the Gradle build tool, please file them here https://github.com/gradle/gradle/issues
