### ISSUE TITLE
Handle nested empty src directories in one pass

### ISSUE THREAD

**Issue by itshields** [runningcode/gradle-doctor#96]
If a project has a source directory like: `foo/bar/baz` where `baz` is empty, `bar` contains only `baz` and nothing else, and `foo` contains only `bar` and nothing else (i.e. they are also empty aside from the empty folder they contain), this will be flagged as an empty source directory, and the suggested solution is removing `foo/bar/baz`. However, this only removes `baz`, and the next run will flag `foo/bar` as an empty directory and prompt you to remove `bar`, and so on. This means it takes a few runs to clear out all of these folders if you go purely by the doctor's orders. It would be great if the plugin could recognize the entire tree as being empty and prompt you to remove the "root" empty directory (and subfolders) in the first pass.

**Comment by runningcode** [comment]
This is a good idea. I recognize this is an issue and have encountered it myself but I haven't prioritized it since it is usually a one time cleanup. PRs welcome!
